import { randomUUID } from 'node:crypto';
import type { DatabasePool } from '@kcml/database';
import { inTransaction } from '@kcml/database';
import { browserActionInputSchema, canonicalDigest, type CanonicalJsonValue } from '@kcml/schemas';
import { assertObservationFence, browserObservationSchema, targetReferenceSchema, type ActionOutcome, type BrowserObservation, type TargetReference } from '@kcml/browser-runtime-contracts';
import { DomainError } from '@kcml/domain';

function bytes(value:string):Buffer{return Buffer.from(value.slice(7),'hex');}
function json(value:unknown):CanonicalJsonValue{return JSON.parse(JSON.stringify(value,(_key,item)=>typeof item==='bigint'?item.toString():item)) as CanonicalJsonValue;}

export interface BrowserAdapter{observe(sessionId:string):Promise<BrowserObservation>;dispatch(sessionId:string,action:string,target:TargetReference|null,payload:Record<string,unknown>):Promise<{possibleSideEffect:boolean;evidence:Record<string,unknown>}>;}

export class BrowserInteractionService{
  public constructor(private readonly pool:DatabasePool,private readonly adapter:BrowserAdapter){}
  public async observe(sessionId:string):Promise<BrowserObservation>{const observation=browserObservationSchema.parse(await this.adapter.observe(sessionId));await inTransaction(this.pool,'SERIALIZABLE',async client=>{const sessionResult=await client.query(`SELECT * FROM kcml.browser_session WHERE id=$1 FOR UPDATE`,[sessionId]);const session=sessionResult.rows[0];if(!session)throw new DomainError('BROWSER_SESSION_NOT_FOUND','Browser session does not exist',404);if(observation.contextGeneration!==BigInt(session.context_generation)||observation.documentEpoch<BigInt(session.document_epoch))throw new DomainError('BROWSER_OBSERVATION_FENCE_INVALID','Observation belongs to a stale browser lineage',409);await client.query(`INSERT INTO kcml.browser_observation(id,session_id,observation_revision,context_generation,page_id,page_generation,frame_id,document_epoch,url,title,semantic_snapshot,screenshot_artifact_id,network_summary,console_summary,canonical_digest,observed_at)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)`,[observation.observationId,sessionId,observation.observationRevision.toString(),observation.contextGeneration.toString(),observation.pageId,observation.pageGeneration.toString(),observation.frameId,observation.documentEpoch.toString(),observation.url,observation.title,observation.semanticSnapshot,observation.screenshotArtifactId,observation.networkSummary,observation.consoleSummary,bytes(observation.digest),observation.observedAt]);await client.query(`UPDATE kcml.browser_session SET current_url=$2,current_page_id=$3,current_frame_id=$4,document_epoch=$5,observation_revision=$6,state_version=state_version+1,updated_at=clock_timestamp() WHERE id=$1`,[sessionId,observation.url,observation.pageId,observation.frameId,observation.documentEpoch.toString(),observation.observationRevision.toString()]);});return observation;}
  public async action(inputValue:unknown,logicalOperationId=randomUUID()):Promise<ActionOutcome>{const input=browserActionInputSchema.parse(inputValue);return inTransaction(this.pool,'SERIALIZABLE',async client=>{const sessionResult=await client.query(`SELECT * FROM kcml.browser_session WHERE id=$1 FOR UPDATE`,[input.sessionId]);const session=sessionResult.rows[0];if(!session)throw new DomainError('BROWSER_SESSION_NOT_FOUND','Browser session does not exist',404);if(BigInt(session.control_epoch)!==input.expectedControlEpoch||BigInt(session.document_epoch)!==input.expectedDocumentEpoch||BigInt(session.observation_revision)!==input.expectedObservationRevision)throw new DomainError('BROWSER_FENCE_CONFLICT','Browser control/document/observation fence changed',409,'REFRESH_AND_RETRY_NEW_COMMAND');if(!['AI','OWNER','AUTOMATION'].includes(session.control_holder))throw new DomainError('BROWSER_CONTROL_UNAVAILABLE','No current control holder',409);let target:TargetReference|null=null;if(input.targetReferenceId){const result=await client.query(`SELECT * FROM kcml.browser_target_reference WHERE id=$1 AND session_id=$2`,[input.targetReferenceId,input.sessionId]);const row=result.rows[0];if(!row)throw new DomainError('BROWSER_TARGET_NOT_FOUND','Target reference does not exist',404);target=targetReferenceSchema.parse({targetReferenceId:row.id,sessionId:row.session_id,pageId:row.page_id,frameId:row.frame_id,documentEpoch:row.document_epoch,semanticDescription:row.semantic_description,locatorAst:row.locator_ast,fingerprint:`sha256:${Buffer.from(row.target_fingerprint).toString('hex')}`,createdFromObservationRevision:row.created_from_observation_revision});const latest=await client.query(`SELECT * FROM kcml.browser_observation WHERE session_id=$1 ORDER BY observation_revision DESC LIMIT 1`,[input.sessionId]);if(latest.rows[0])assertObservationFence(target,browserObservationSchema.parse({...latest.rows[0],observationId:latest.rows[0].id,sessionId:latest.rows[0].session_id,observationRevision:latest.rows[0].observation_revision,contextGeneration:latest.rows[0].context_generation,pageId:latest.rows[0].page_id,pageGeneration:latest.rows[0].page_generation,frameId:latest.rows[0].frame_id,documentEpoch:latest.rows[0].document_epoch,semanticSnapshot:latest.rows[0].semantic_snapshot,networkSummary:latest.rows[0].network_summary,consoleSummary:latest.rows[0].console_summary,screenshotArtifactId:latest.rows[0].screenshot_artifact_id,digest:`sha256:${Buffer.from(latest.rows[0].canonical_digest).toString('hex')}`,observedAt:new Date(latest.rows[0].observed_at).toISOString()}));}
      const actionId=randomUUID();await client.query(`INSERT INTO kcml.browser_action_run(id,session_id,logical_operation_id,action,target_reference_id,payload,expected_control_epoch,expected_document_epoch,expected_observation_revision,dispatch_phase)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'PRECONDITION_VERIFIED')`,[actionId,input.sessionId,logicalOperationId,input.action,input.targetReferenceId,input.payload,input.expectedControlEpoch.toString(),input.expectedDocumentEpoch.toString(),input.expectedObservationRevision.toString()]);
      await client.query(`UPDATE kcml.browser_action_run SET dispatch_phase='DISPATCH_AUTHORIZED',state_version=state_version+1 WHERE id=$1`,[actionId]);
      const dispatched=await this.adapter.dispatch(input.sessionId,input.action,target,input.payload);const phase=dispatched.possibleSideEffect?'RECONCILING':'OUTCOME_OBSERVED';await client.query(`UPDATE kcml.browser_action_run SET dispatch_phase=$2,earliest_mutation_trigger=$3,outcome=$4,state_version=state_version+1,updated_at=clock_timestamp() WHERE id=$1`,[actionId,phase,dispatched.possibleSideEffect?input.action:null,dispatched.evidence]);return{actionId,phase,possibleSideEffect:dispatched.possibleSideEffect,retryAllowed:!dispatched.possibleSideEffect,observation:null,evidence:dispatched.evidence};});}
  public async transferControl(sessionId:string,expectedControlEpoch:bigint,holder:'AI'|'OWNER'|'AUTOMATION',ttlSeconds=300):Promise<unknown>{const result=await this.pool.query(`UPDATE kcml.browser_session SET control_holder=$3,control_epoch=control_epoch+1,control_fence=control_fence+1,control_expires_at=clock_timestamp()+make_interval(secs=>$4),lifecycle=$5,state_version=state_version+1,updated_at=clock_timestamp() WHERE id=$1 AND control_epoch=$2 RETURNING *`,[sessionId,expectedControlEpoch.toString(),holder,ttlSeconds,holder==='AI'?'AI_CONTROLLED':holder==='OWNER'?'OWNER_CONTROLLED':'AUTOMATION_CONTROLLED']);if(result.rowCount!==1)throw new DomainError('BROWSER_CONTROL_EPOCH_CONFLICT','Browser control changed',409,'REFRESH_AND_RETRY_NEW_COMMAND');return result.rows[0];}
}
