import { createHash, randomUUID } from 'node:crypto';
import type { DatabasePool } from '@kcml/database';
import { allocateContiguousSequence, inTransaction } from '@kcml/database';
import type { ResponsesRuntime } from '@kcml/openai-runtime';
import type { AuthorityLineage } from '@kcml/agentic-authority';
import { DomainError } from '@kcml/domain';

function digestBytes(hex:string):Buffer{return Buffer.from(hex.replace(/^sha256:/u,''),'hex');}

export const generationTransitions:Readonly<Record<string,readonly string[]>>={
  INTAKE:['DISCOVERY','CANCELLED_FINAL'],DISCOVERY:['SPECIFICATION','MANUAL_REVIEW','CANCELLED_FINAL'],SPECIFICATION:['APPROVAL_REQUIRED','MANUAL_REVIEW','CANCELLED_FINAL'],
  APPROVAL_REQUIRED:['PLANNING','SPECIFICATION','CANCELLED_FINAL'],PLANNING:['IMPLEMENTING','MANUAL_REVIEW','CANCELLED_FINAL'],IMPLEMENTING:['VALIDATING','MANUAL_REVIEW','CANCELLED_FINAL'],
  VALIDATING:['IMPLEMENTING','ACTIVATING','FAILED_FINAL','MANUAL_REVIEW','CANCELLED_FINAL'],ACTIVATING:['SUCCEEDED','VALIDATING','FAILED_FINAL','MANUAL_REVIEW'],
  SUCCEEDED:[],FAILED_FINAL:[],CANCELLED_FINAL:[],MANUAL_REVIEW:['DISCOVERY','SPECIFICATION','PLANNING','IMPLEMENTING','VALIDATING','ACTIVATING','FAILED_FINAL']
};

export class GenerationOrchestrator{
  public constructor(private readonly pool:DatabasePool,private readonly openai:ResponsesRuntime){}
  public async transition(jobId:string,expectedStateVersion:bigint,next:string,evidence:unknown):Promise<unknown>{return inTransaction(this.pool,'SERIALIZABLE',async client=>{const result=await client.query(`SELECT * FROM kcml.generation_job WHERE id=$1 FOR UPDATE`,[jobId]);const job=result.rows[0];if(!job)throw new DomainError('GENERATION_JOB_NOT_FOUND','Generation job does not exist',404);if(BigInt(job.state_version)!==expectedStateVersion)throw new DomainError('STATE_VERSION_CONFLICT','Generation job changed',409,'REFRESH_AND_RETRY_NEW_COMMAND');if(!(generationTransitions[job.lifecycle]??[]).includes(next))throw new DomainError('GENERATION_TRANSITION_INVALID',`${job.lifecycle} cannot transition to ${next}`,409);if(next==='PLANNING'&&!job.approved_spec_revision_id)throw new DomainError('SPEC_APPROVAL_REQUIRED','Exact specification revision approval is required',409);const progress:Record<string,number>={INTAKE:3,DISCOVERY:12,SPECIFICATION:28,APPROVAL_REQUIRED:38,PLANNING:45,IMPLEMENTING:67,VALIDATING:84,ACTIVATING:94,SUCCEEDED:100,FAILED_FINAL:100,CANCELLED_FINAL:100,MANUAL_REVIEW:Number(job.progress)};const updated=await client.query(`UPDATE kcml.generation_job SET lifecycle=$2,current_phase=$2,progress=$3,blocker=CASE WHEN $2='MANUAL_REVIEW' THEN $4::jsonb ELSE NULL END,state_version=state_version+1,updated_at=clock_timestamp() WHERE id=$1 RETURNING *`,[jobId,next,progress[next]??job.progress,JSON.stringify(evidence)]);const sequence=await allocateContiguousSequence(client,'GENERATION_CHECKPOINT',jobId,'SEQUENCE');await client.query(`INSERT INTO kcml.generation_checkpoint(generation_job_id,sequence,phase,workspace_revision,payload,payload_digest)VALUES($1,$2,$3,$4,$5,digest(convert_to($6,'UTF8'),'sha256'))`,[jobId,sequence.toString(),next,String(BigInt(job.state_version)+1n),{transition:{from:job.lifecycle,to:next},evidence},JSON.stringify({transition:{from:job.lifecycle,to:next},evidence})]);return updated.rows[0];});}
  public async executeModel(jobId:string,model:string,instructions:string,input:unknown,authority:AuthorityLineage,onEvent?:(event:unknown)=>void):Promise<unknown>{const job=await this.pool.query(`SELECT * FROM kcml.generation_job WHERE id=$1`,[jobId]);if(!job.rows[0])throw new DomainError('GENERATION_JOB_NOT_FOUND','Generation job does not exist',404);return this.openai.create({parentRunId:jobId,ownerKind:'GENERATION_PHASE',model,instructions,input,authority},async event=>{onEvent?.(event);});}

  public async recordWorkspaceFile(jobId:string,path:string,content:string,expectedRevision:bigint):Promise<unknown>{
    if(!path||path.startsWith('/')||path.includes('..'))throw new DomainError('GENERATION_WORKSPACE_PATH_INVALID','Workspace path must be relative and contained',422,'DO_NOT_RETRY');
    const contentDigest=createHash('sha256').update(content,'utf8').digest('hex');
    return inTransaction(this.pool,'SERIALIZABLE',async client=>{const job=(await client.query(`SELECT state_version FROM kcml.generation_job WHERE id=$1 FOR UPDATE`,[jobId])).rows[0];if(!job)throw new DomainError('GENERATION_JOB_NOT_FOUND','Generation job does not exist',404);const revision=await allocateContiguousSequence(client,'GENERATION_WORKSPACE',jobId,'REVISION');if(revision!==expectedRevision+1n)throw new DomainError('GENERATION_WORKSPACE_REVISION_CONFLICT','Workspace revision is not the expected successor',409,'REFRESH_AND_RETRY_NEW_COMMAND');const parent=(await client.query(`SELECT id FROM kcml.generation_workspace_revision WHERE job_id=$1 AND revision_number=$2`,[jobId,expectedRevision.toString()])).rows[0]?.id??null;const revisionId=randomUUID();await client.query(`INSERT INTO kcml.generation_workspace_revision(id,parent_id,stable_key,display_name,job_id,revision_number,parent_revision_id,source_tree_digest,canonical_digest) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8)`,[revisionId,jobId,`workspace:${jobId}:${revision}`,String(revision),jobId,revision.toString(),parent,digestBytes(contentDigest)]);const fileId=randomUUID();await client.query(`INSERT INTO kcml.generation_workspace_file(id,parent_id,stable_key,display_name,workspace_revision_id,relative_path,file_type,executable,content_storage,content_reference,size_bytes,content_digest,source_classification,canonical_digest) VALUES($1,$2,$3,$4,$2,$4,'SOURCE',false,'INLINE_TEXT',$5,$6,$7,'MODEL_GENERATED',$7)`,[fileId,revisionId,`file:${jobId}:${revision}:${path}`,path,content,Buffer.byteLength(content,'utf8'),digestBytes(contentDigest)]);return {revision:revision.toString(),fileId,path,contentDigest};});
  }

  public async validateCandidate(jobId:string,candidate:unknown):Promise<unknown>{
    if(typeof candidate!=='object'||candidate===null||Array.isArray(candidate))throw new DomainError('GENERATION_CANDIDATE_INVALID','Candidate must be a structured contract object',422,'DO_NOT_RETRY');
    const value=candidate as Record<string,unknown>;const kind=String(value.kind??'');const allowed=new Set(['COMPONENT','MCP_SERVER','MCP_TOOL','MCP_RESOURCE','MCP_PROMPT','AI_AGENT','AUTOMATION']);if(!allowed.has(kind))throw new DomainError('GENERATION_CANDIDATE_KIND_INVALID','Candidate kind is not a canonical SSOT kind',422,'DO_NOT_RETRY');if(typeof value.proposedIdentity!=='object'||value.proposedIdentity===null||typeof value.revisionPayload!=='object'||value.revisionPayload===null)throw new DomainError('GENERATION_CANDIDATE_FIELDS_MISSING','Candidate identity and revision payload are required',422,'DO_NOT_RETRY');
    return inTransaction(this.pool,'SERIALIZABLE',async client=>{const job=(await client.query(`SELECT id FROM kcml.generation_job WHERE id=$1 FOR SHARE`,[jobId])).rows[0];if(!job)throw new DomainError('GENERATION_JOB_NOT_FOUND','Generation job does not exist',404);const digest=createHash('sha256').update(JSON.stringify(candidate),'utf8').digest('hex');const digestValue=digestBytes(digest);const candidateId=randomUUID();await client.query(`INSERT INTO kcml.generation_contract_candidate(id,parent_id,stable_key,display_name,job_id,candidate_kind,proposed_identity,revision_payload,revision_digest,specification_paths,validation_state,verification_state,integration_state,canonical_digest) VALUES($1,$2,$3,$4,$2,$5,$6,$7,$8,$9,'PENDING','PENDING','PENDING',$8)`,[candidateId,jobId,`candidate:${jobId}:${digest}`,`candidate-${jobId}`,kind,value.proposedIdentity,value.revisionPayload,digestValue,Array.isArray(value.specificationPaths)?value.specificationPaths:[]]);const validationId=randomUUID();const validationDigest=createHash('sha256').update(`${candidateId}:${digest}`,'utf8').digest();await client.query(`INSERT INTO kcml.generation_validation_run(id,parent_id,stable_key,display_name,job_id,candidate_id,gate_catalog_version,state,started_at,canonical_digest) VALUES($1,$2,$3,$4,$2,$5,'SSOT-55','RUNNING',clock_timestamp(),$6)`,[validationId,jobId,`validation:${jobId}:${digest}`,`validation-${jobId}`,candidateId,validationDigest]);return {candidateId,validationId,digest};});
  }

  public async integrateCandidate(jobId:string,candidateId:string,workspaceRevision:bigint):Promise<unknown>{
    return inTransaction(this.pool,'SERIALIZABLE',async client=>{const artifact=(await client.query(`SELECT id,relative_path,content_digest,size_bytes,media_type,immutable_storage_path FROM kcml.generation_artifact WHERE generation_job_id=$1 AND workspace_revision=$2`,[jobId,workspaceRevision.toString()])).rows;if(!artifact.length)throw new DomainError('GENERATION_ARTIFACTS_MISSING','Integration requires persisted workspace artifacts',409,'DO_NOT_RETRY');const evidence={workspaceRevision:workspaceRevision.toString(),artifactCount:artifact.length,status:'INTEGRATED'};const updated=await client.query(`UPDATE kcml.generation_contract_candidate SET integration_state='INTEGRATED',integration_evidence=$2,state_version=state_version+1,updated_at=clock_timestamp() WHERE id=$1 AND job_id=$3 AND integration_state='PENDING' RETURNING id`,[candidateId,evidence,jobId]);if(updated.rowCount!==1)throw new DomainError('GENERATION_CANDIDATE_INTEGRATION_CONFLICT','Candidate is missing or no longer pending integration',409,'REFRESH_AND_RETRY_NEW_COMMAND');return {candidateId,workspaceRevision:workspaceRevision.toString(),artifactCount:artifact.length,status:'INTEGRATED'};});
  }

  public async activateGeneration(jobId:string,candidateSnapshot:unknown,previousSnapshot:unknown,activationEpoch:bigint):Promise<unknown>{
    return inTransaction(this.pool,'SERIALIZABLE',async client=>{const id=randomUUID();await client.query(`INSERT INTO kcml.generation_activation_set(id,state,previous_snapshot,candidate_snapshot,membership,rollback_plan,activation_epoch,platform_incarnation_id,application_deployment_epoch) SELECT $1,'READY',$2,$3,$4,$5,$6,p.platform_incarnation_id,d.current_epoch FROM kcml.platform_incarnation p CROSS JOIN kcml.application_deployment_head d WHERE p.singleton_key=1 AND d.singleton_key=1`,[id,previousSnapshot,candidateSnapshot,{jobId}, {jobId,kind:'GENERATION_ROLLBACK'},activationEpoch.toString()]);await client.query(`UPDATE kcml.generation_job SET lifecycle='ACTIVATING',current_phase='ACTIVATING',state_version=state_version+1,updated_at=clock_timestamp() WHERE id=$1 AND lifecycle IN('VALIDATING','IMPLEMENTING')`,[jobId]);return {activationSetId:id,jobId,state:'READY',activationEpoch:activationEpoch.toString()};});
  }

  public async cleanupOrphans(jobId:string):Promise<unknown>{
    return inTransaction(this.pool,'SERIALIZABLE',async client=>{const cleanupId=randomUUID();const heads=(await client.query(`SELECT p.platform_incarnation_id,d.current_epoch FROM kcml.platform_incarnation p CROSS JOIN kcml.application_deployment_head d WHERE p.singleton_key=1 AND d.singleton_key=1`)).rows[0];if(!heads)throw new DomainError('AUTHORITY_HEADS_MISSING','Platform authority heads are missing',503,'RETRY_SAME_OPERATION');await client.query(`INSERT INTO kcml.cleanup_operation(id,parent_kind,parent_id,status,platform_incarnation_id,application_deployment_epoch) VALUES($1,'GENERATION_JOB',$2,'RUNNING',$3,$4)`,[cleanupId,jobId,heads.platform_incarnation_id,heads.current_epoch]);const result=await client.query(`SELECT f.id FROM kcml.generation_workspace_file f JOIN kcml.generation_workspace_revision r ON r.id=f.workspace_revision_id WHERE r.job_id=$1 AND f.deleted_at IS NOT NULL`,[jobId]);await client.query(`UPDATE kcml.cleanup_operation SET status='CLOSED',closure_evidence=$2,updated_at=clock_timestamp() WHERE id=$1`,[cleanupId,{orphanCount:result.rowCount??0,jobId}]);return {cleanupId,orphanCount:result.rowCount??0};});
  }
}
