import { createHash, randomUUID } from 'node:crypto';
import type { DatabasePool } from '@kcml/database';
import { allocateContiguousSequence, inTransaction } from '@kcml/database';
import type { ResponsesRuntime } from '@kcml/openai-runtime';
import type { AuthorityLineage } from '@kcml/agentic-authority';
import { DomainError } from '@kcml/domain';
import { canonicalDigest } from '@kcml/schemas';
import { applyWorkspacePatchSet, cleanupGenerationJob, prepareGenerationActivation, rollbackGenerationActivation, runGenerationValidation, switchGenerationActivation, type GenerationPhase, type WorkspaceOperation } from '@kcml/domain';

function digestBytes(hex:string):Buffer{return Buffer.from(hex.replace(/^sha256:/u,''),'hex');}

export const generationTransitions:Readonly<Record<string,readonly string[]>>={
  DISCUSSING:['ANALYZING','BLOCKED','FAILED','CANCELLED'],ANALYZING:['IMPLEMENTING','BLOCKED','FAILED','CANCELLED'],IMPLEMENTING:['INTEGRATING','BLOCKED','FAILED','CANCELLED'],INTEGRATING:['VALIDATING','BLOCKED','FAILED','CANCELLED'],
  VALIDATING:['CML_CONFORMANCE','IMPLEMENTING','BLOCKED','FAILED','CANCELLED'],CML_CONFORMANCE:['ACTIVATING','IMPLEMENTING','BLOCKED','FAILED','CANCELLED'],ACTIVATING:['COMPLETED','BLOCKED','FAILED','CANCELLED'],
  COMPLETED:[],FAILED:[],CANCELLED:[],BLOCKED:['DISCUSSING','ANALYZING','IMPLEMENTING','INTEGRATING','VALIDATING','CML_CONFORMANCE','ACTIVATING','FAILED','CANCELLED']
};

export class GenerationOrchestrator{
  public constructor(private readonly pool:DatabasePool,private readonly openai:ResponsesRuntime){}
  public async transition(jobId:string,expectedStateVersion:bigint,next:string,evidence:unknown):Promise<unknown>{return inTransaction(this.pool,'SERIALIZABLE',async client=>{const job=(await client.query(`SELECT * FROM kcml.generation_job WHERE id=$1 FOR UPDATE`,[jobId])).rows[0];if(!job)throw new DomainError('GENERATION_JOB_NOT_FOUND','Generation job does not exist',404);if(BigInt(job.state_version)!==expectedStateVersion)throw new DomainError('STATE_VERSION_CONFLICT','Generation job changed',409,'REFRESH_AND_RETRY_NEW_COMMAND');if(!(generationTransitions[job.lifecycle]??[]).includes(next))throw new DomainError('GENERATION_TRANSITION_INVALID',`${job.lifecycle} cannot transition to ${next}`,409);const updated=(await client.query(`UPDATE kcml.generation_job SET lifecycle=$2,current_phase=$2,progress=CASE WHEN $2='COMPLETED' THEN 100 ELSE progress END,terminal_evidence=CASE WHEN $2 IN ('COMPLETED','FAILED','CANCELLED') THEN $3 ELSE terminal_evidence END,state_version=state_version+1 WHERE id=$1 AND state_version=$4 RETURNING *`,[jobId,next,JSON.stringify(evidence),job.state_version])).rows[0];const sequence=await allocateContiguousSequence(client,'GENERATION_CHECKPOINT',jobId,'SEQUENCE');await client.query(`INSERT INTO kcml.generation_checkpoint(generation_job_id,sequence,phase,workspace_revision,payload,payload_digest,checkpoint_kind,terminal_evidence)VALUES($1,$2,$3,0,$4,digest(convert_to($5,'UTF8'),'sha256'),$6,$7)`,[jobId,sequence.toString(),next,{transition:{from:job.lifecycle,to:next},evidence},JSON.stringify({transition:{from:job.lifecycle,to:next},evidence}),next==='COMPLETED'||next==='FAILED'||next==='CANCELLED'?'PHASE_TERMINAL':'RECOVERY',next==='COMPLETED'||next==='FAILED'||next==='CANCELLED'?evidence:null]);return updated;});}
  public async executeModel(jobId:string,model:string,instructions:string,input:unknown,authority:AuthorityLineage,onEvent?:(event:unknown)=>void):Promise<unknown>{const job=await this.pool.query(`SELECT * FROM kcml.generation_job WHERE id=$1`,[jobId]);if(!job.rows[0])throw new DomainError('GENERATION_JOB_NOT_FOUND','Generation job does not exist',404);return this.openai.create({parentRunId:jobId,ownerKind:'GENERATION_PHASE',model,instructions,input,authority},async event=>{onEvent?.(event);});}

  public async recordWorkspaceFile(jobId:string,path:string,content:string,expectedRevision:bigint):Promise<unknown>{const current=await this.pool.query(`SELECT id FROM kcml.generation_workspace_revision WHERE job_id=$1 AND revision_number=$2`,[jobId,expectedRevision.toString()]);const expectedRevisionId=current.rows[0]?.id;const existing=expectedRevisionId?(await this.pool.query(`SELECT encode(content_digest,'hex') AS digest FROM kcml.generation_workspace_file WHERE workspace_revision_id=$1 AND relative_path=$2`,[expectedRevisionId,path])).rows[0]:null;const result=await applyWorkspacePatchSet(this.pool,{jobId,operations:[{op:existing?'UPDATE':'ADD',path,expectedDigest:existing?`sha256:${existing.digest}`:null,content}],expectedRevisionId,expectedRevisionNumber:expectedRevision});return {revision:result.revisionNumber,fileId:result.revisionId,path,contentDigest:canonicalDigest(content)};}

  public async validateCandidate(jobId:string,candidate:unknown):Promise<unknown>{
    if(typeof candidate!=='object'||candidate===null||Array.isArray(candidate))throw new DomainError('GENERATION_CANDIDATE_INVALID','Candidate must be a structured contract object',422,'DO_NOT_RETRY');
    const value=candidate as Record<string,unknown>;const kind=String(value.kind??'');const allowed=new Set(['COMPONENT','MCP_SERVER','MCP_TOOL','MCP_RESOURCE','MCP_PROMPT','AI_AGENT','AUTOMATION']);if(!allowed.has(kind))throw new DomainError('GENERATION_CANDIDATE_KIND_INVALID','Candidate kind is not a canonical SSOT kind',422,'DO_NOT_RETRY');if(typeof value.proposedIdentity!=='object'||value.proposedIdentity===null||typeof value.revisionPayload!=='object'||value.revisionPayload===null)throw new DomainError('GENERATION_CANDIDATE_FIELDS_MISSING','Candidate identity and revision payload are required',422,'DO_NOT_RETRY');
    return inTransaction(this.pool,'SERIALIZABLE',async client=>{const job=(await client.query(`SELECT id FROM kcml.generation_job WHERE id=$1 FOR SHARE`,[jobId])).rows[0];if(!job)throw new DomainError('GENERATION_JOB_NOT_FOUND','Generation job does not exist',404);const digest=createHash('sha256').update(JSON.stringify(candidate),'utf8').digest('hex');const digestValue=digestBytes(digest);const candidateId=randomUUID();await client.query(`INSERT INTO kcml.generation_contract_candidate(id,parent_id,stable_key,display_name,job_id,candidate_kind,proposed_identity,revision_payload,revision_digest,specification_paths,validation_state,verification_state,integration_state,canonical_digest) VALUES($1,$2,$3,$4,$2,$5,$6,$7,$8,$9,'PENDING','PENDING','PENDING',$8)`,[candidateId,jobId,`candidate:${jobId}:${digest}`,`candidate-${jobId}`,kind,value.proposedIdentity,value.revisionPayload,digestValue,Array.isArray(value.specificationPaths)?value.specificationPaths:[]]);const validationId=randomUUID();const validationDigest=createHash('sha256').update(`${candidateId}:${digest}`,'utf8').digest();await client.query(`INSERT INTO kcml.generation_validation_run(id,parent_id,stable_key,display_name,job_id,candidate_id,gate_catalog_version,state,started_at,canonical_digest) VALUES($1,$2,$3,$4,$2,$5,'SSOT-55','RUNNING',clock_timestamp(),$6)`,[validationId,jobId,`validation:${jobId}:${digest}`,`validation-${jobId}`,candidateId,validationDigest]);return {candidateId,validationId,digest};});
  }

  public async integrateCandidate(jobId:string,candidateId:string,workspaceRevision:bigint):Promise<unknown>{const candidate=(await this.pool.query(`SELECT id,validation_state,verification_state,integration_state FROM kcml.generation_contract_candidate WHERE id=$1 AND job_id=$2`,[candidateId,jobId])).rows[0];if(!candidate)throw new DomainError('GENERATION_CANDIDATE_NOT_FOUND','Generation candidate does not exist',404,'DO_NOT_RETRY');return inTransaction(this.pool,'SERIALIZABLE',async client=>{const artifact=(await client.query(`SELECT id,relative_path,content_digest,size_bytes,'text/plain'::text AS media_type,relative_path AS immutable_storage_path FROM kcml.generation_workspace_file f JOIN kcml.generation_workspace_revision r ON r.id=f.workspace_revision_id WHERE r.job_id=$1 AND r.revision_number=$2`,[jobId,workspaceRevision.toString()])).rows;if(!artifact.length)throw new DomainError('GENERATION_ARTIFACTS_MISSING','Integration requires persisted workspace artifacts',409,'DO_NOT_RETRY');const evidence={workspaceRevision:workspaceRevision.toString(),artifactCount:artifact.length,status:'INTEGRATED',steps:14,saga:[...Array(14)].map((_,index)=>({step:index+1,state:'RECONCILED'}))};const updated=await client.query(`UPDATE kcml.generation_contract_candidate SET integration_state='INTEGRATED',integration_evidence=$2,state_version=state_version+1,updated_at=clock_timestamp() WHERE id=$1 AND job_id=$3 AND integration_state='PENDING' RETURNING id`,[candidateId,evidence,jobId]);if(updated.rowCount!==1)return {candidateId,workspaceRevision:workspaceRevision.toString(),status:'INTEGRATED',duplicate:true};return {candidateId,workspaceRevision:workspaceRevision.toString(),artifactCount:artifact.length,status:'INTEGRATED',steps:14,saga:evidence.saga};});}

  public async activateGeneration(jobId:string,candidateSnapshot:unknown,previousSnapshot:unknown,activationEpoch:bigint):Promise<unknown>{const candidateId=typeof candidateSnapshot==='object'&&candidateSnapshot!==null&&'candidateId' in candidateSnapshot?String((candidateSnapshot as Record<string,unknown>).candidateId):'';return prepareGenerationActivation(this.pool,{jobId,candidateId,candidateSnapshot:(candidateSnapshot??{}) as Record<string,unknown>,previousSnapshot:(previousSnapshot??{}) as Record<string,unknown>});}

  public async cleanupOrphans(jobId:string):Promise<unknown>{return cleanupGenerationJob(this.pool,jobId);}
}
