import type { FaultPointDeclaration } from '@kcml/schemas';

/**
 * The only source of fault-point identity. Keep this list explicit: the
 * Contract Pack compiler reads it and validates every source marker.
 */
export const faultPointDeclarations = [
  {
    faultPointId: 'FP-DOMAIN-COMPONENT-REGISTER-ADMISSION-BEFORE', faultPointName: 'domain.component.register.admission-validate.before', operationName: 'component.register', stateMachineId: 'SM-COMPONENT', phase: 'admission.validate', side: 'before',
    sourceLocation: { repositoryPath: 'packages/domain/src/operations.ts', symbol: 'CanonicalOperationService.execute', marker: 'FAULT_POINT:DOMAIN_ADMISSION_BEFORE' }, possibleEffectClass: 'NONE', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'STALE_IDENTITY', 'DATABASE_RESTART'], expectedRecoveryOracleId: 'ORACLE-DOMAIN-COMMAND', expectedCanonicalOutcomeClasses: ['CONFIRMED_NOT_APPLIED', 'FAILED_FINAL'], requiredDirectStateQueries: ['domain_idempotency_record', 'domain_command'], requiredCleanupChecks: ['NO_DOMAIN_COMMAND', 'NO_QUEUE_ITEM', 'NO_OUTBOX_GAP'], testCaseIds: ['FAULT-COVERAGE-DOMAIN-ADMISSION'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://49/formalni-korektnost-stavu-soubehu-a-obnovy/crash-point', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-DOMAIN-COMPONENT-REGISTER-ADMISSION-AFTER', faultPointName: 'domain.component.register.admission-validate.after', operationName: 'component.register', stateMachineId: 'SM-COMPONENT', phase: 'admission.validate', side: 'after',
    sourceLocation: { repositoryPath: 'packages/domain/src/operations.ts', symbol: 'CanonicalOperationService.execute', marker: 'FAULT_POINT:DOMAIN_ADMISSION_AFTER' }, possibleEffectClass: 'NONE', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'STALE_IDENTITY', 'DATABASE_RESTART'], expectedRecoveryOracleId: 'ORACLE-DOMAIN-COMMAND', expectedCanonicalOutcomeClasses: ['CONFIRMED_NOT_APPLIED', 'FAILED_FINAL'], requiredDirectStateQueries: ['domain_idempotency_record', 'domain_command'], requiredCleanupChecks: ['NO_DOMAIN_COMMAND', 'NO_QUEUE_ITEM', 'NO_OUTBOX_GAP'], testCaseIds: ['FAULT-COVERAGE-DOMAIN-ADMISSION'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://49/formalni-korektnost-stavu-soubehu-a-obnovy/crash-point', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-DOMAIN-COMPONENT-REGISTER-QUEUE-BEFORE', faultPointName: 'domain.component.register.queue-claim.before', operationName: 'component.register', stateMachineId: 'SM-COMPONENT', phase: 'queue_claim', side: 'before',
    sourceLocation: { repositoryPath: 'packages/domain/src/operations.ts', symbol: 'CanonicalCommandWorker.runOnce', marker: 'FAULT_POINT:DOMAIN_QUEUE_CLAIM_BEFORE' }, possibleEffectClass: 'QUEUE_CLAIM', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'DUPLICATE', 'STALE_IDENTITY', 'DATABASE_RESTART'], expectedRecoveryOracleId: 'ORACLE-QUEUE-CLAIM', expectedCanonicalOutcomeClasses: ['CONFIRMED_NOT_APPLIED', 'RETRY_SAME_OPERATION'], requiredDirectStateQueries: ['queue_item', 'concurrency_claim', 'domain_command'], requiredCleanupChecks: ['NO_STALE_QUEUE_LEASE'], testCaseIds: ['FAULT-COVERAGE-DOMAIN-QUEUE'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://50.36/failure-injection-crash-matrix', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-DOMAIN-COMPONENT-REGISTER-QUEUE-AFTER', faultPointName: 'domain.component.register.queue-claim.after', operationName: 'component.register', stateMachineId: 'SM-COMPONENT', phase: 'queue_claim', side: 'after',
    sourceLocation: { repositoryPath: 'packages/domain/src/operations.ts', symbol: 'CanonicalCommandWorker.runOnce', marker: 'FAULT_POINT:DOMAIN_QUEUE_CLAIM_AFTER' }, possibleEffectClass: 'QUEUE_CLAIM', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'DUPLICATE', 'STALE_IDENTITY', 'DATABASE_RESTART'], expectedRecoveryOracleId: 'ORACLE-QUEUE-CLAIM', expectedCanonicalOutcomeClasses: ['CONFIRMED_NOT_APPLIED', 'RETRY_SAME_OPERATION'], requiredDirectStateQueries: ['queue_item', 'concurrency_claim', 'domain_command'], requiredCleanupChecks: ['NO_STALE_QUEUE_LEASE'], testCaseIds: ['FAULT-COVERAGE-DOMAIN-QUEUE'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://50.36/failure-injection-crash-matrix', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-DOMAIN-COMPONENT-REGISTER-CHECKPOINT-BEFORE', faultPointName: 'domain.component.register.checkpoint-persist.before', operationName: 'component.register', stateMachineId: 'SM-COMPONENT', phase: 'checkpoint.persist', side: 'before',
    sourceLocation: { repositoryPath: 'packages/domain/src/operations.ts', symbol: 'CanonicalCommandWorker.applyInCommandTransaction', marker: 'FAULT_POINT:DOMAIN_CHECKPOINT_BEFORE' }, possibleEffectClass: 'LOCAL_STATE_COMMIT', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'DATABASE_RESTART', 'STALE_IDENTITY'], expectedRecoveryOracleId: 'ORACLE-DOMAIN-COMMAND', expectedCanonicalOutcomeClasses: ['CONFIRMED_NOT_APPLIED', 'CONFIRMED_APPLIED', 'MANUAL_REVIEW'], requiredDirectStateQueries: ['domain_command_execution_checkpoint', 'domain_command'], requiredCleanupChecks: ['CHECKPOINT_DIGEST_VALID'], testCaseIds: ['FAULT-COVERAGE-DOMAIN-CHECKPOINT'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://49.25/crash-point-decision-matrix', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-DOMAIN-COMPONENT-REGISTER-CHECKPOINT-AFTER', faultPointName: 'domain.component.register.checkpoint-persist.after', operationName: 'component.register', stateMachineId: 'SM-COMPONENT', phase: 'checkpoint.persist', side: 'after',
    sourceLocation: { repositoryPath: 'packages/domain/src/operations.ts', symbol: 'CanonicalCommandWorker.applyInCommandTransaction', marker: 'FAULT_POINT:DOMAIN_CHECKPOINT_AFTER' }, possibleEffectClass: 'LOCAL_STATE_COMMIT', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'DATABASE_RESTART', 'STALE_IDENTITY'], expectedRecoveryOracleId: 'ORACLE-DOMAIN-COMMAND', expectedCanonicalOutcomeClasses: ['CONFIRMED_APPLIED', 'MANUAL_REVIEW'], requiredDirectStateQueries: ['domain_command_execution_checkpoint', 'domain_command'], requiredCleanupChecks: ['CHECKPOINT_DIGEST_VALID'], testCaseIds: ['FAULT-COVERAGE-DOMAIN-CHECKPOINT'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://49.25/crash-point-decision-matrix', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-DOMAIN-COMPONENT-REGISTER-TERMINAL-BEFORE', faultPointName: 'domain.component.register.terminal-commit.before', operationName: 'component.register', stateMachineId: 'SM-COMPONENT', phase: 'terminal.commit', side: 'before',
    sourceLocation: { repositoryPath: 'packages/domain/src/operations.ts', symbol: 'CanonicalCommandWorker.complete', marker: 'FAULT_POINT:DOMAIN_TERMINAL_BEFORE' }, possibleEffectClass: 'TERMINAL_COMMIT', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'DATABASE_RESTART', 'STALE_IDENTITY'], expectedRecoveryOracleId: 'ORACLE-DOMAIN-COMMAND', expectedCanonicalOutcomeClasses: ['CONFIRMED_APPLIED', 'MANUAL_REVIEW'], requiredDirectStateQueries: ['domain_command', 'domain_idempotency_record', 'queue_item'], requiredCleanupChecks: ['CONCURRENCY_CLAIM_RELEASED', 'ACTIVATION_DOMAIN_CLOSED'], testCaseIds: ['FAULT-COVERAGE-DOMAIN-TERMINAL'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://49.25/crash-point-decision-matrix', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-DOMAIN-COMPONENT-REGISTER-TERMINAL-AFTER', faultPointName: 'domain.component.register.terminal-commit.after', operationName: 'component.register', stateMachineId: 'SM-COMPONENT', phase: 'terminal.commit', side: 'after',
    sourceLocation: { repositoryPath: 'packages/domain/src/operations.ts', symbol: 'CanonicalCommandWorker.complete', marker: 'FAULT_POINT:DOMAIN_TERMINAL_AFTER' }, possibleEffectClass: 'TERMINAL_COMMIT', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'DATABASE_RESTART', 'STALE_IDENTITY'], expectedRecoveryOracleId: 'ORACLE-DOMAIN-COMMAND', expectedCanonicalOutcomeClasses: ['CONFIRMED_APPLIED'], requiredDirectStateQueries: ['domain_command', 'domain_idempotency_record', 'queue_item'], requiredCleanupChecks: ['CONCURRENCY_CLAIM_RELEASED', 'ACTIVATION_DOMAIN_CLOSED'], testCaseIds: ['FAULT-COVERAGE-DOMAIN-TERMINAL'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://49.25/crash-point-decision-matrix', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-GENERATION-JOB-TRANSITION-BEFORE', faultPointName: 'generation.job.transition.state-transition.before', operationName: 'generation.phase.start', stateMachineId: 'SM-GENERATION_JOB', phase: 'state.transition', side: 'before',
    sourceLocation: { repositoryPath: 'packages/generation-orchestrator/src/index.ts', symbol: 'GenerationOrchestrator.transition', marker: 'FAULT_POINT:GENERATION_TRANSITION_BEFORE' }, possibleEffectClass: 'LOCAL_STATE_COMMIT', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'DATABASE_RESTART', 'STALE_IDENTITY'], expectedRecoveryOracleId: 'ORACLE-GENERATION-STATE', expectedCanonicalOutcomeClasses: ['CONFIRMED_NOT_APPLIED', 'CONFIRMED_APPLIED', 'MANUAL_REVIEW'], requiredDirectStateQueries: ['generation_job', 'generation_checkpoint'], requiredCleanupChecks: ['CHECKPOINT_SEQUENCE_CONTIGUOUS'], testCaseIds: ['FAULT-COVERAGE-GENERATION-TRANSITION'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://49.25/crash-point-decision-matrix', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-GENERATION-JOB-TRANSITION-AFTER', faultPointName: 'generation.job.transition.state-transition.after', operationName: 'generation.phase.start', stateMachineId: 'SM-GENERATION_JOB', phase: 'state.transition', side: 'after',
    sourceLocation: { repositoryPath: 'packages/generation-orchestrator/src/index.ts', symbol: 'GenerationOrchestrator.transition', marker: 'FAULT_POINT:GENERATION_TRANSITION_AFTER' }, possibleEffectClass: 'LOCAL_STATE_COMMIT', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'DATABASE_RESTART', 'STALE_IDENTITY'], expectedRecoveryOracleId: 'ORACLE-GENERATION-STATE', expectedCanonicalOutcomeClasses: ['CONFIRMED_APPLIED'], requiredDirectStateQueries: ['generation_job', 'generation_checkpoint'], requiredCleanupChecks: ['CHECKPOINT_SEQUENCE_CONTIGUOUS'], testCaseIds: ['FAULT-COVERAGE-GENERATION-TRANSITION'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://49.25/crash-point-decision-matrix', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-OPENAI-MODEL-SUBMIT-BEFORE', faultPointName: 'openai.model.submit.dispatch-trigger.before', operationName: 'generation.model.execute', stateMachineId: 'SM-GENERATION_JOB', phase: 'dispatch.trigger', side: 'before',
    sourceLocation: { repositoryPath: 'packages/openai-runtime/src/index.ts', symbol: 'ResponsesRuntime.create', marker: 'FAULT_POINT:OPENAI_SUBMIT_BEFORE' }, possibleEffectClass: 'PROVIDER_REQUEST', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'TRANSPORT_DISCONNECT', 'PROVIDER_FAILURE', 'CREDENTIAL_EXPIRY'], expectedRecoveryOracleId: 'ORACLE-OPENAI-SUBMIT', expectedCanonicalOutcomeClasses: ['CONFIRMED_NOT_APPLIED', 'UNKNOWN', 'MANUAL_REVIEW'], requiredDirectStateQueries: ['ai_model_call', 'ai_model_event'], requiredCleanupChecks: ['NO_BLIND_PROVIDER_RESUBMIT'], testCaseIds: ['FAULT-COVERAGE-OPENAI-SUBMIT'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://52.33/presna-crash-recovery-matrice-provider-callu', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-OPENAI-MODEL-SUBMIT-AFTER', faultPointName: 'openai.model.submit.dispatch-trigger.after', operationName: 'generation.model.execute', stateMachineId: 'SM-GENERATION_JOB', phase: 'dispatch.trigger', side: 'after',
    sourceLocation: { repositoryPath: 'packages/openai-runtime/src/index.ts', symbol: 'ResponsesRuntime.create', marker: 'FAULT_POINT:OPENAI_SUBMIT_AFTER' }, possibleEffectClass: 'PROVIDER_REQUEST', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'TRANSPORT_DISCONNECT', 'PROVIDER_FAILURE', 'CREDENTIAL_EXPIRY'], expectedRecoveryOracleId: 'ORACLE-OPENAI-SUBMIT', expectedCanonicalOutcomeClasses: ['CONFIRMED_APPLIED', 'UNKNOWN', 'MANUAL_REVIEW'], requiredDirectStateQueries: ['ai_model_call', 'ai_model_event'], requiredCleanupChecks: ['PROVIDER_HANDLE_RECONCILED'], testCaseIds: ['FAULT-COVERAGE-OPENAI-SUBMIT'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://52.33/presna-crash-recovery-matrice-provider-callu', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-BROWSER-ACTION-DISPATCH-BEFORE', faultPointName: 'browser.action.dispatch.dispatch-trigger.before', operationName: 'browser.action.dispatchPhase', stateMachineId: 'SM-BROWSER_SESSION', phase: 'dispatch.trigger', side: 'before',
    sourceLocation: { repositoryPath: 'packages/browser-interaction/src/index.ts', symbol: 'BrowserInteractionService.action', marker: 'FAULT_POINT:BROWSER_DISPATCH_BEFORE' }, possibleEffectClass: 'BROWSER_MUTATION', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'TRANSPORT_DISCONNECT', 'BROWSER_LIFECYCLE_RACE', 'STALE_IDENTITY'], expectedRecoveryOracleId: 'ORACLE-BROWSER-ACTION', expectedCanonicalOutcomeClasses: ['CONFIRMED_NOT_APPLIED', 'CONFIRMED_APPLIED', 'UNKNOWN'], requiredDirectStateQueries: ['browser_action_run', 'browser_session'], requiredCleanupChecks: ['NO_PRESSED_INPUT', 'NO_STALE_ACTION_LEASE'], testCaseIds: ['FAULT-COVERAGE-BROWSER-DISPATCH'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://50.36/failure-injection-crash-matrix', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-BROWSER-ACTION-DISPATCH-AFTER', faultPointName: 'browser.action.dispatch.dispatch-trigger.after', operationName: 'browser.action.dispatchPhase', stateMachineId: 'SM-BROWSER_SESSION', phase: 'dispatch.trigger', side: 'after',
    sourceLocation: { repositoryPath: 'packages/browser-interaction/src/index.ts', symbol: 'BrowserInteractionService.action', marker: 'FAULT_POINT:BROWSER_DISPATCH_AFTER' }, possibleEffectClass: 'BROWSER_MUTATION', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'TRANSPORT_DISCONNECT', 'BROWSER_LIFECYCLE_RACE', 'STALE_IDENTITY'], expectedRecoveryOracleId: 'ORACLE-BROWSER-ACTION', expectedCanonicalOutcomeClasses: ['CONFIRMED_APPLIED', 'UNKNOWN'], requiredDirectStateQueries: ['browser_action_run', 'browser_session'], requiredCleanupChecks: ['POSTCONDITION_OR_MANUAL_REVIEW'], testCaseIds: ['FAULT-COVERAGE-BROWSER-DISPATCH'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://50.36/failure-injection-crash-matrix', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-BROWSER-ACTION-READBACK-BEFORE', faultPointName: 'browser.action.dispatch.effect-readback.before', operationName: 'browser.action.dispatchPhase', stateMachineId: 'SM-BROWSER_SESSION', phase: 'effect.readback', side: 'before',
    sourceLocation: { repositoryPath: 'packages/browser-interaction/src/index.ts', symbol: 'BrowserInteractionService.action', marker: 'FAULT_POINT:BROWSER_READBACK_BEFORE' }, possibleEffectClass: 'BROWSER_READBACK', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'TRANSPORT_DISCONNECT', 'BROWSER_LIFECYCLE_RACE'], expectedRecoveryOracleId: 'ORACLE-BROWSER-ACTION', expectedCanonicalOutcomeClasses: ['CONFIRMED_APPLIED', 'UNKNOWN'], requiredDirectStateQueries: ['browser_action_run', 'browser_observation'], requiredCleanupChecks: ['ACTION_OUTCOME_DURABLE'], testCaseIds: ['FAULT-COVERAGE-BROWSER-READBACK'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://13/browser-interaction-plane', 'ssot://54/fault-catalog/fault-point'],
  },
  {
    faultPointId: 'FP-BROWSER-ACTION-READBACK-AFTER', faultPointName: 'browser.action.dispatch.effect-readback.after', operationName: 'browser.action.dispatchPhase', stateMachineId: 'SM-BROWSER_SESSION', phase: 'effect.readback', side: 'after',
    sourceLocation: { repositoryPath: 'packages/browser-interaction/src/index.ts', symbol: 'BrowserInteractionService.action', marker: 'FAULT_POINT:BROWSER_READBACK_AFTER' }, possibleEffectClass: 'BROWSER_READBACK', applicableFaultKinds: ['PROCESS_KILL', 'TIMEOUT', 'TRANSPORT_DISCONNECT', 'BROWSER_LIFECYCLE_RACE'], expectedRecoveryOracleId: 'ORACLE-BROWSER-ACTION', expectedCanonicalOutcomeClasses: ['CONFIRMED_APPLIED', 'UNKNOWN'], requiredDirectStateQueries: ['browser_action_run', 'browser_observation'], requiredCleanupChecks: ['ACTION_OUTCOME_DURABLE'], testCaseIds: ['FAULT-COVERAGE-BROWSER-READBACK'], coverageStatus: 'COVERED', requirementIds: [], authoritySourceRefs: ['ssot://13/browser-interaction-plane', 'ssot://54/fault-catalog/fault-point'],
  },
] as const satisfies readonly FaultPointDeclaration[];

const faultPointsById: Map<string, FaultPointDeclaration> = new Map(faultPointDeclarations.map((point) => [point.faultPointId, point]));
export function faultPointById(faultPointId: string): FaultPointDeclaration {
  const point = faultPointsById.get(faultPointId);
  if (!point) throw new Error(`FAULT_POINT_UNKNOWN:${faultPointId}`);
  return point;
}
